name: mssql
services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    container_name: mssqldb
    hostname: mssqldb
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '${DB_ADMIN_PASS}'
      MSSQL_PID: ${MSSQL_PRODUCT_ID:-Developer}
    volumes:
      - /var/lib/srv/$USER/docker/mssql/server/latest/rootfs/data/db/mssql:/var/opt/sqlserver
      - /var/lib/srv/$USER/docker/mssql/server/latest/rootfs/config/mssql/initdb:/usr/src/app/docker-entrypoint-initdb.d
    extra_hosts:
      - 'localhost:172.17.0.1'
      - 'host.docker.internal:host-gateway'

  client:
    image: adminer:latest
    container_name: mssql-client
    hostname: mssql-client
    environment:
      - ADMINER_DESIGN=dracula
      - ADMINER_DEFAULT_DB_HOST=mssqldb
    depends_on:
      - db
    ports:
      - 172.17.0.1:59085:8080
    extra_hosts:
      - 'localhost:172.17.0.1'
      - 'host.docker.internal:host-gateway'
